version: '2'

services:

    wsgiserver:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        volumes:
            - static_volume:/app/backend/server/static
        ports:
            - "8000:8000"
    frontend:
        build: 
            context: .
            dockerfile: ./docker/frontend/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
volumes:
    static_volume: {}